# Definindo o nome do workflow
name: Teste Workflow Daniel

# Definindo quando o workflow será disparado
on:
  push:
    branches: [main]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando job de teste
    runs-on: ubunto-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'danrossi02'
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
