# Definindo o nome do workflow
name: Teste Workflow Daniel

# Definindo quando o workflow será disparado
on:
  push:
    branches: [main]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando job de teste
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Alterando política de execução
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

      - name: Executando um comando simples
        run: echo "Olá, mundo! Este é o meu primeiro job no GitHub Actions"
