# Definindo o nome do workflow
name: Teste Workflow Daniel

# Definindo quando o workflow será disparado
on:
  push:
    branches: [main]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando job de teste
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
